#部署zk-finance2的List
apiVersion: v1
kind: List
items:
#zk-finance2数据库存储
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    creationTimestamp: null
    labels:
      group: test
      project: test
      provider: "mysql-zk-finance2"
    name: "test-mysql-zk-finance2-pv"
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: "mysql-zk-finance2-data"
      namespace: test
    hostPath:
      path: "/var/lib/docker/data/mysql-storage/test/zk-finance2/"
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      group: test
      project: test
      provider: "mysql-zk-finance2"
    name: "mysql-zk-finance2-data"
    namespace: test
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: "test-mysql-zk-finance2-pv"
