#部署coc的List
apiVersion: v1
kind: List
items:
#coc数据库存储
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    creationTimestamp: null
    labels:
      group: test
      project: test
      provider: "coc-mysql"
    name: "test-coc-mysql-pv"
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: "coc-mysql-data"
      namespace: test
    hostPath:
      path: "/mnt/data/test-storage/coc-mysql/"
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      group: test
      project: test
      provider: "coc-mysql"
    name: "coc-mysql-data"
    namespace: test
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: "test-coc-mysql-pv"
