#部署cas-sso-server的List
apiVersion: v1
kind: List
items:
#cas-sso-server数据库存储
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    creationTimestamp: null
    labels:
      group: dev
      project: dev
      provider: "cas-sso-server-mysql"
    name: "dev-cas-sso-server-mysql-pv"
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: "cas-sso-server-mysql-data"
      namespace: dev
    hostPath:
      path: "/mnt/data/dev-storage/cas-sso-server-mysql/"
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      group: dev
      project: dev
      provider: "cas-sso-server-mysql"
    name: "cas-sso-server-mysql-data"
    namespace: dev
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: "dev-cas-sso-server-mysql-pv"
