#部署redis的List
apiVersion: v1
kind: List
items:
#redis数据库存储
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    creationTimestamp: null
    labels:
      group: dev
      project: dev
      provider: "dev-redis"
    name: "dev-redis-pv"
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: "redis-data"
      namespace: dev
    hostPath:
      path: "/mnt/data/dev-storage/redis/"
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      group: dev
      project: dev
      provider: "dev-redis"
    name: "redis-data"
    namespace: dev
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: "dev-redis-pv"
