#部署zk-finance的List
apiVersion: v1
kind: List
items:
#zk-finance数据库存储
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    creationTimestamp: null
    labels:
      group: dev
      project: dev
      provider: "zk-finance-mysql"
    name: "dev-zk-finance-mysql-pv"
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: "zk-finance-mysql-data"
      namespace: dev
    hostPath:
      path: "/mnt/data/dev-storage/zk-finance-mysql/"
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      group: dev
      project: dev
      provider: "zk-finance-mysql"
    name: "zk-finance-mysql-data"
    namespace: dev
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: "dev-zk-finance-mysql-pv"
#zk-finance存储
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    creationTimestamp: null
    labels:
      group: dev
      project: dev
      provider: "zk-finance"
    name: "dev-zk-finance-pv"
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: "zk-finance-data"
      namespace: dev
    hostPath:
      path: "/mnt/data/product-storage/nginx/html/dev-zk-finance/"
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      group: dev
      project: dev
      provider: "zk-finance"
    name: "zk-finance-data"
    namespace: dev
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: "dev-zk-finance-pv"
