#部署qcdafront模板
kind: Template
apiVersion: v1
metadata:
  name: qcdafront-ephemeral
  creationTimestamp: null
  annotations:
    openshift.io/display-name: Qcdafront App (Ephemeral)
    description: |-
      All resource for qcdafront, with ephemeral storage.
    iconClass: icon-jenkins
    tags: qcdafront
labels:
  template: dev-qcdafront-ephemeral-template
  group: dev
message: Simple deploy Qcdafront App
#参数
parameters:
#当前项目名称
- name: NAMESPACE
  displayName: Current Project Namespace
  description: Name of the current project namespace.
  value: dev
#当前模板名称
- name: TEMPLATE
  displayName: Current Template Name
  description: Name of the current template name.
  value: dev-qcdafront-ephemeral-template
#默认服务账户名称
- name: DEFAULT_NAME
  displayName: Default ServiceAccount Name
  description: Name of the default serviceaccount.
  value: default
#Qcdafront容器名称
- name: FRONT_SERVICE
  displayName: Qcdafront Service Name
  description: The name of the OpenShift Service exposed for the Qcdafront container.
  value: qcdafront
#日志信息存放路径
- name: LOG_MESSAGE
  displayName: Termination Message Path
  description: Maximum amount of memory the container can use.
  value: /dev/termination-log
#部署超时
- name: TIME_OUT
  displayName: timeout seconds
  description: Deployment params timeout seconds
  value: '600'
#镜像所在项目名称
- name: IMAGE_NAMESPACE
  displayName: The ImageStream Namespace
  description: The OpenShift Namespace where the ImageStream resides.
  value: openshift
#CST时区
- name: SERVER_TIMEZONE
  displayName: CST Timezone
  description: China Standard Time for POD
  value: Asia/Shanghai
objects:
#Qcdafront的路由
- apiVersion: v1
  kind: Route
  metadata:
    name: "${FRONT_SERVICE}-http"
    namespace: "${NAMESPACE}"
    creationTimestamp: null
    labels:
      app: "${FRONT_SERVICE}"
    annotations:
      description: Route for Qcdafront http service.
      openshift.io/host.generated: 'true'
  spec:
    host: qcdafront.shanghaiqixiu.org
    to:
      kind: Service
      name: "${NAMESPACE}-${FRONT_SERVICE}"
      weigth: 100
    port:
      targetPort: "${FRONT_SERVICE}-8080-tcp"
    wildcardPolicy: None
#Qcdafront的部署配置
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "${FRONT_SERVICE}"
    namespace: "${NAMESPACE}"
    creationTimestamp: null
    labels:
      app: "${FRONT_SERVICE}"
      group: "${NAMESPACE}"
      template: "${TEMPLATE}"
    annotations:
      description: The DeploymentConfig for Qcdafront
  spec:
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: "${TIME_OUT}"
      resources: {}
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - "${FRONT_SERVICE}"
          from:
            kind: ImageStreamTag
            namespace: "${NAMESPACE}"
            name: "${FRONT_SERVICE}:latest"
          lastTriggeredImage: ''
    replicas: 1
    test: false
    selector:
      app: "${FRONT_SERVICE}"
      deploymentconfig: "${FRONT_SERVICE}"
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: "${FRONT_SERVICE}"
          deploymentconfig: "${FRONT_SERVICE}"
      spec:
        containers:
          - name: "${FRONT_SERVICE}"
            image: ' '
            ports:
              - containerPort: 8080
                protocol: TCP
            env:
              - name: TZ
                value: "${SERVER_TIMEZONE}"
            resources: {}
            livenessProbe:
              httpGet:
                path: /
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 30
              timeoutSeconds: 5
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 5
            readinessProbe:
              httpGet:
                path: /
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 30
              timeoutSeconds: 5
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 5
            terminationMessagePath: "${LOG_MESSAGE}"
            imagePullPolicy: Always
            securityContext:
              capabilities: {}
              privileged: true
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        serviceAccountName: "${DEFAULT_NAME}"
        serviceAccount: "${DEFAULT_NAME}"
        securityContext: {}
  status: {}
#Qcdafront的服务
- apiVersion: v1
  kind: Service
  metadata:
    name: "${NAMESPACE}-${FRONT_SERVICE}"
    namespace: "${NAMESPACE}"
    creationTimestamp: null
    labels:
      app: "${FRONT_SERVICE}"
      group: "${NAMESPACE}"
      template: "${TEMPLATE}"
    annotations:
      description: the Service for Qcdafront
  spec:
    ports:
      - name: "${FRONT_SERVICE}-8080-tcp"
        protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      app: "${FRONT_SERVICE}"
      deploymentconfig: "${FRONT_SERVICE}"
    clusterIP: 172.30.101.12
    type: ClusterIP
    sessionAffinity: None
