#部署redis的List
apiVersion: v1
kind: List
items:
#redis数据库存储
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    creationTimestamp: null
    labels:
      group: base
      project: base
      provider: "base-redis"
    name: "base-redis-pv"
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: "base-redis-data"
      namespace: base
    hostPath:
      path: "/mnt/data/base-storage/redis/"
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      group: base
      project: base
      provider: "base-redis"
    name: "base-redis-data"
    namespace: base
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: "base-redis-pv"
