apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "zk-qualification", "namespace": "", "kind": "DeploymentConfig"}]'
    name: zk-qualification-pipeline
  spec:
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: https://github.com/boy12371/openshift-cicd.git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: jenkinsfile/zk-qualification
