#部署coc的List
apiVersion: v1
kind: List
items:
#coc数据库存储
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    creationTimestamp: null
    labels:
      group: product
      project: product
      provider: "coc-mysql"
    name: "product-coc-mysql-pv"
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: "coc-mysql-data"
      namespace: product
    hostPath:
      path: "/mnt/data/product-storage/coc-mysql/"
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      group: product
      project: product
      provider: "coc-mysql"
    name: "coc-mysql-data"
    namespace: product
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: "product-coc-mysql-pv"
