#部署finance的List
apiVersion: v1
kind: List
items:
#finance数据库存储
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    creationTimestamp: null
    labels:
      group: product
      project: product
      provider: "finance-mysql"
    name: "product-finance-mysql-pv"
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: "finance-mysql-data"
      namespace: product
    hostPath:
      path: "/mnt/data/product-storage/finance-mysql/"
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      group: product
      project: product
      provider: "finance-mysql"
    name: "finance-mysql-data"
    namespace: product
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: "product-finance-mysql-pv"
#finance存储
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    creationTimestamp: null
    labels:
      group: product
      project: product
      provider: "finance"
    name: "product-finance-pv"
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: "finance-data"
      namespace: product
    hostPath:
      path: "/mnt/data/product-storage/nginx/html/finance/"
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      group: product
      project: product
      provider: "finance"
    name: "finance-data"
    namespace: product
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: "product-finance-pv"
