apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    creationTimestamp: null
    labels:
      project: default
      provider: docker-registry
    name: default-registry-pv
  spec:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: 100Gi
    claimRef:
      kind: PersistentVolumeClaim
      name: default-registry-data
      namespace: default
    hostPath:
      path: /mnt/data/openshift-storage/origin-docker-registry
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      project: default
      provider: docker-registry
    name: default-registry-data
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 100Gi
    volumeName: default-registry-pv
