#部署jenkins模板
kind: Template
apiVersion: v1
metadata:
  name: jenkins-persistent
  creationTimestamp: null
  annotations:
    openshift.io/display-name: Jenkins App (Persistent)
    description: |-
      All resource for jenkins with persistent storage.
    iconClass: icon-jenkins
    tags: instant-app,jenkins
labels:
  template: cicd-jenkins-persistent-template
  group: cicd
message: Simple deploy Jenkins App
#参数
parameters:
#当前项目名称
- name: NAMESPACE
  displayName: Current Project Namespace
  description: Name of the current project namespace.
  value: cicd
#当前模板名称
- name: TEMPLATE
  displayName: Current Template Name
  description: Name of the current template name.
  value: cicd-jenkins-persistent-template
#Jenkins容器名称
- name: JENKINS_SERVICE
  displayName: Jenkins Service Name
  description: The name of the OpenShift Service exposed for the Jenkins container.
  value: jenkins
#激活openshift登录
- name: ENABLE_OAUTH
  displayName: Enable OAuth
  description: |-
    Whether to enable OAuth OpenShift integration. If false, the static
    account 'admin' will be initialized with the password 'password'.
  value: 'true'
#日志信息存放路径
- name: LOG_MESSAGE
  displayName: Termination Message Path
  description: Maximum amount of memory the container can use.
  value: /dev/termination-log
#部署超时
- name: TIME_OUT
  displayName: timeout seconds
  description: Deployment params timeout seconds
  value: '600'
#CST时区
- name: SERVER_TIMEZONE
  displayName: CST Timezone
  description: China Standard Time for POD
  value: Asia/Shanghai
objects:
#创建服务账户
- apiVersion: v1
  kind: ServiceAccount
  groupNames: "${NAMESPACE}"
  metadata:
    annotations:
      serviceaccounts.openshift.io/oauth-redirectreference.jenkins: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"${JENKINS_SERVICE}"}}'
    creationTimestamp: null
    labels:
      app: "${JENKINS_SERVICE}"
      template: "${TEMPLATE}"
    name: "${JENKINS_SERVICE}"
    namespace: "${NAMESPACE}"
#创建角色绑定
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    labels:
      app: "${JENKINS_SERVICE}"
      template: "${TEMPLATE}"
    name: "${JENKINS_SERVICE}_edit"
    namespace: "${NAMESPACE}"
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: "${JENKINS_SERVICE}"
    namespace: "${NAMESPACE}"
  userNames:
  - system:serviceaccount:cicd:jenkins
#Jenkins的路由
- apiVersion: v1
  kind: Route
  metadata:
    name: "${JENKINS_SERVICE}-http"
    namespace: "${NAMESPACE}"
    creationTimestamp: null
    labels:
      app: "${JENKINS_SERVICE}"
    annotations:
      description: Route for Jenkins http service.
      openshift.io/host.generated: 'true'
  spec:
    to:
      kind: Service
      name: "${JENKINS_SERVICE}"
      weigth: 100
    port:
      targetPort: "${JENKINS_SERVICE}-8080-tcp"
    wildcardPolicy: None
#Jenkins存储
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    creationTimestamp: null
    labels:
      group: "${NAMESPACE}"
      project: "${NAMESPACE}"
      provider: "${JENKINS_SERVICE}"
      template: "${TEMPLATE}"
    name: "${NAMESPACE}-${JENKINS_SERVICE}-pv"
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 15Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: "${JENKINS_SERVICE}-data"
      namespace: "${NAMESPACE}"
    hostPath:
      path: "/mnt/data/cicd-storage/jenkins/"
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      group: "${NAMESPACE}"
      project: "${NAMESPACE}"
      provider: "${JENKINS_SERVICE}"
      template: "${TEMPLATE}"
    name: "${JENKINS_SERVICE}-data"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 15Gi
    volumeName: "${NAMESPACE}-${JENKINS_SERVICE}-pv"
#Jenkins的部署配置
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "${JENKINS_SERVICE}"
    namespace: "${NAMESPACE}"
    creationTimestamp: null
    labels:
      app: "${JENKINS_SERVICE}"
      group: "${NAMESPACE}"
      template: "${TEMPLATE}"
    annotations:
      description: The DeploymentConfig for Jenkins
  spec:
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: "${TIME_OUT}"
      resources: {}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - "${JENKINS_SERVICE}"
        from:
          kind: ImageStreamTag
          namespace: "${NAMESPACE}"
          name: jenkins-blueocean:latest
        lastTriggeredImage: ''
    replicas: 1
    test: false
    selector:
      app: "${JENKINS_SERVICE}"
      deploymentconfig: "${JENKINS_SERVICE}"
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: "${JENKINS_SERVICE}"
          deploymentconfig: "${JENKINS_SERVICE}"
      spec:
        volumes:
          - name: "${JENKINS_SERVICE}-data"
            persistentVolumeClaim:
              claimName: "${JENKINS_SERVICE}-data"
        containers:
          - name: "${JENKINS_SERVICE}"
            image: ' '
            ports:
              - containerPort: 8080
                protocol: TCP
            env:
              - name: OPENSHIFT_ENABLE_OAUTH
                value: "${ENABLE_OAUTH}"
              - name: OPENSHIFT_ENABLE_REDIRECT_PROMPT
                value: 'true'
              - name: KUBERNETES_MASTER
                value: https://kubernetes.default:443
              - name: KUBERNETES_TRUST_CERTIFICATES
                value: 'true'
              - name: JNLP_SERVICE_NAME
                value: "${JENKINS_SERVICE}-jnlp"
              - name: TZ
                value: "${SERVER_TIMEZONE}"
            resources: {}
            volumeMounts:
              - name: "${JENKINS_SERVICE}-data"
                mountPath: /var/lib/jenkins
            livenessProbe:
              httpGet:
                path: /login
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 420
              timeoutSeconds: 3
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 30
            readinessProbe:
              httpGet:
                path: /login
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 3
              timeoutSeconds: 3
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            terminationMessagePath: "${LOG_MESSAGE}"
            imagePullPolicy: IfNotPresent
            securityContext:
              capabilities: {}
              privileged: true
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        serviceAccountName: "${JENKINS_SERVICE}"
        serviceAccount: "${JENKINS_SERVICE}"
        securityContext: {}
  status: {}
#Jenkins服务
- apiVersion: v1
  kind: Service
  metadata:
    name: "${JENKINS_SERVICE}"
    namespace: "${NAMESPACE}"
    creationTimestamp: null
    labels:
      app: "${JENKINS_SERVICE}"
      template: "${TEMPLATE}"
    annotations:
      description: the Service for Jenkins
      service.alpha.openshift.io/dependencies: '[{"name": "${JENKINS_SERVICE}-jnlp", "namespace": "", "kind": "Service"}]'
      service.openshift.io/infrastructure: 'true'
  spec:
    ports:
      - name: "${JENKINS_SERVICE}-8080-tcp"
        protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      app: "${JENKINS_SERVICE}"
      deploymentconfig: "${JENKINS_SERVICE}"
    clusterIP: 172.30.100.12
    type: ClusterIP
    sessionAffinity: None
#Jenkins的Jnlp服务
- apiVersion: v1
  kind: Service
  metadata:
    name: "${JENKINS_SERVICE}-jnlp"
    namespace: "${NAMESPACE}"
    creationTimestamp: null
    labels:
      app: "${JENKINS_SERVICE}"
      template: "${TEMPLATE}"
    annotations:
      description: the Service for Jenkins Jnlp
  spec:
    ports:
      - name: "${JENKINS_SERVICE}-jnlp-5000-tcp"
        protocol: TCP
        port: 50000
        targetPort: 50000
    selector:
      app: "${JENKINS_SERVICE}"
      deploymentconfig: "${JENKINS_SERVICE}"
    clusterIP: 172.30.100.13
    type: ClusterIP
    sessionAffinity: None
