#部署nexus模板
kind: Template
apiVersion: v1
metadata:
  name: nexus-persistent
  creationTimestamp: null
  annotations:
    openshift.io/display-name: Nexus App (Persistent)
    description: |-
      All resource for nexus, with persistent storage.
    iconClass: icon-jenkins
    tags: nexus
labels:
  template: cicd-nexus-persistent-template
  group: cicd
message: Simple deploy Nexus App
#参数
parameters:
#当前项目名称
- name: NAMESPACE
  displayName: Current Project Namespace
  description: Name of the current project namespace.
  value: cicd
#当前模板名称
- name: TEMPLATE
  displayName: Current Template Name
  description: Name of the current template name.
  value: cicd-nexus-persistent-template
#Nexus容器名称
- name: NEXUS_SERVICE
  displayName: Nexus Service Name
  description: The name of the OpenShift Service exposed for the Nexus container.
  value: nexus
#日志信息存放路径
- name: LOG_MESSAGE
  displayName: Termination Message Path
  description: Maximum amount of memory the container can use.
  value: /dev/termination-log
#部署超时
- name: TIME_OUT
  displayName: timeout seconds
  description: Deployment params timeout seconds
  value: '600'
#镜像所在项目名称
- name: IMAGE_NAMESPACE
  displayName: Cicd ImageStream Namespace
  description: The OpenShift Namespace where the Cicd ImageStream resides.
  value: openshift
#CST时区
- name: SERVER_TIMEZONE
  displayName: CST Timezone
  description: China Standard Time for POD
  value: Asia/Shanghai
objects:
#创建服务账户
- apiVersion: v1
  kind: ServiceAccount
  groupNames: "${NAMESPACE}"
  metadata:
    name: "${NAMESPACE}user"
#创建角色绑定
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    labels:
      group: "${NAMESPACE}"
      template: "${TEMPLATE}"
    name: "${NAMESPACE}user_edit"
    namespace: "${NAMESPACE}"
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: "${NAMESPACE}user"
    namespace: "${NAMESPACE}"
#Nexus的路由
- apiVersion: v1
  kind: Route
  metadata:
    name: "${NEXUS_SERVICE}"
    namespace: "${NAMESPACE}"
    creationTimestamp: null
    labels:
      app: "${NEXUS_SERVICE}"
    annotations:
      description: Route for Nexus http service.
      openshift.io/host.generated: 'true'
  spec:
    to:
      kind: Service
      name: "${NEXUS_SERVICE}"
      weigth: 100
    port:
      targetPort: "${NEXUS_SERVICE}-tcp"
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
#Nexus存储
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    creationTimestamp: null
    labels:
      group: "${NAMESPACE}"
      project: "${NAMESPACE}"
      provider: "${NEXUS_SERVICE}"
      template: "${TEMPLATE}"
    name: "${NAMESPACE}-${NEXUS_SERVICE}-pv"
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 20Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: "${NEXUS_SERVICE}-data"
      namespace: "${NAMESPACE}"
    hostPath:
      path: "/var/lib/docker/data/${NEXUS_SERVICE}-storage/${NAMESPACE}/"
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      group: "${NAMESPACE}"
      project: "${NAMESPACE}"
      provider: "${NEXUS_SERVICE}"
      template: "${TEMPLATE}"
    name: "${NEXUS_SERVICE}-data"
    namespace: "${NAMESPACE}"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    volumeName: "${NAMESPACE}-${NEXUS_SERVICE}-pv"
#Nexus的部署配置
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "${NEXUS_SERVICE}"
    namespace: "${NAMESPACE}"
    creationTimestamp: null
    labels:
      app: "${NEXUS_SERVICE}"
      group: "${NAMESPACE}"
      template: "${TEMPLATE}"
    annotations:
      description: The DeploymentConfig for Nexus
  spec:
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: "${TIME_OUT}"
      resources: {}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - "${NEXUS_SERVICE}"
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_NAMESPACE}"
          name: nexus:2.14.4
        lastTriggeredImage: ''
    replicas: 1
    test: false
    selector:
      app: "${NEXUS_SERVICE}"
      deploymentconfig: "${NEXUS_SERVICE}"
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: "${NEXUS_SERVICE}"
          deploymentconfig: "${NEXUS_SERVICE}"
      spec:
        volumes:
          - name: "${NEXUS_SERVICE}-data"
            persistentVolumeClaim:
              claimName: "${NEXUS_SERVICE}-data"
        containers:
          - name: "${NEXUS_SERVICE}"
            image: ' '
            ports:
              - containerPort: 8081
                protocol: TCP
            env:
              - name: CONTEXT_PATH
                value: /
              - name: TZ
                value: "${SERVER_TIMEZONE}"
            resources:
              limits:
                cpu: '1'
                memory: 512Mi
            volumeMounts:
              - name: "${NEXUS_SERVICE}-data"
                mountPath: /sonatype-work
            livenessProbe:
              httpGet:
                path: /content/groups/public/
                port: 8081
                scheme: HTTP
              initialDelaySeconds: 60
              timeoutSeconds: 5
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 5
            readinessProbe:
              httpGet:
                path: /content/groups/public/
                port: 8081
                scheme: HTTP
              initialDelaySeconds: 60
              timeoutSeconds: 5
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 5
            terminationMessagePath: "${LOG_MESSAGE}"
            imagePullPolicy: IfNotPresent
            securityContext:
              capabilities: {}
              privileged: true
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        serviceAccountName: "${NAMESPACE}user"
        serviceAccount: "${NAMESPACE}user"
        securityContext: {}
  status: {}
#Nexus的服务
- apiVersion: v1
  kind: Service
  metadata:
    name: "${NEXUS_SERVICE}"
    namespace: "${NAMESPACE}"
    creationTimestamp: null
    labels:
      app: "${NEXUS_SERVICE}"
      group: "${NAMESPACE}"
      template: "${TEMPLATE}"
    annotations:
      description: the Service for Nexus
  spec:
    ports:
      - name: "${NEXUS_SERVICE}-tcp"
        protocol: TCP
        port: 8081
        targetPort: 8081
    selector:
      deploymentconfig: "${NEXUS_SERVICE}"
    clusterIP: 172.30.100.13
    type: ClusterIP
    sessionAffinity: None
