#部署zk-finance2模板
kind: Template
apiVersion: v1
metadata:
  name: zk-finance2-persistent
  creationTimestamp: null
  annotations:
    openshift.io/display-name: zk-finance2 App (Persistent)
    description: |-
      All resource for zk-finance2 and mysql, with persistent storage.
    iconClass: icon-jenkins
    tags: mysql, jboss
labels:
  template: dev-zk-finance2-persistent-template
  group: dev
message: Simple deploy zk-finance2
#参数
parameters:
#当前项目名称
- name: NAMESPACE
  displayName: Current Project Namespace
  description: Name of the current project namespace.
  value: dev
#当前模板名称
- name: TEMPLATE
  displayName: Current Template Name
  description: Name of the current template name.
  value: dev-zk-finance2-persistent-template
#当前app名称
- name: APPNAME
  displayName: Current App Name
  description: Name of the current app name.
  value: zk-finance2
#默认服务账户名称
- name: DEFAULT_NAME
  displayName: Default ServiceAccount Name
  description: Name of the default serviceaccount.
  value: default
#MySQL数据库容器名称
- name: MYSQL_SERVICE
  displayName: MySQL Service Name
  description: The name of the OpenShift Service exposed for the MySQL container.
  value: mysql
#Jboss容器名称
- name: JBOSS_SERVICE
  displayName: Jboss Service Name
  description: The name of the OpenShift Service exposed for the Jboss container.
  value: jboss
#Jboss数据库用户名
- name: JBOSS_MYSQL_USER
  displayName: Jboss MySQL User Name
  description: Username for Jboss MySQL backend
  value: userS2Y
#Jboss数据库密码
- name: JBOSS_MYSQL_PASSWORD
  displayName: Jboss MySQL Password
  description: Password for Jboss MySQL backend
  value: JboprQarLvf4Vqg6
#Jboss数据库Root密码
- name: JBOSS_MYSQL_ROOT_PASSWORD
  displayName: Jboss MySQL Root Password
  description: Password for Jboss MySQL Root backend
  value: BttD6qMOcRunnFnd
#Jboss数据库名
- name: JBOSS_MYSQL_DATABASE
  displayName: Jboss MySQL Datebase Name
  description: Datebase Name for Jboss MySQL backend
  value: jboss7JT
#日志信息存放路径
- name: LOG_MESSAGE
  displayName: Termination Message Path
  description: Maximum amount of memory the container can use.
  value: /dev/termination-log
#部署超时
- name: TIME_OUT
  displayName: timeout seconds
  description: Deployment params timeout seconds
  value: '600'
#镜像所在项目名称
- name: IMAGE_NAMESPACE
  displayName: Dev ImageStream Namespace
  description: The OpenShift Namespace where the Dev ImageStream resides.
  value: openshift
#CST时区
- name: SERVER_TIMEZONE
  displayName: CST Timezone
  description: China Standard Time for POD
  value: Asia/Shanghai
objects:
#Jboss的路由
- apiVersion: v1
  kind: Route
  metadata:
    name: "${APPNAME}"
    namespace: "${NAMESPACE}"
    creationTimestamp: null
    labels:
      app: "${APPNAME}"
    annotations:
      description: Route for Jboss http service.
      openshift.io/host.generated: 'true'
  spec:
    to:
      kind: Service
      name: "${NAMESPACE}-${APPNAME}"
      weigth: 100
    port:
      targetPort: "${APPNAME}-tcp"
    tls:
      termination: edge
      certificate: |
        -----BEGIN CERTIFICATE-----
        MIIEZTCCA02gAwIBAgIJAIqh9C24phyUMA0GCSqGSIb3DQEBBQUAMIGdMQswCQYD
        VQQGEwJDTjERMA8GA1UECBMIU2hhbmdoYWkxETAPBgNVBAcTCFNoYW5naGFpMRIw
        EAYDVQQKEwlaSE9OR0xFTEUxFjAUBgNVBAsTDVpIT05HTEVMRS5DT00xJDAiBgkq
        hkiG9w0BCQEWFXN1cHBvcnRAemhvbmdsZWxlLmNvbTEWMBQGA1UEAxMNemhvbmds
        ZWxlLmNvbTAeFw0xNzA2MDIxNzA4MjFaFw0xODA2MDMxNzA4MjFaMIGdMQswCQYD
        VQQGEwJDTjERMA8GA1UECBMIU2hhbmdoYWkxETAPBgNVBAcTCFNoYW5naGFpMRIw
        EAYDVQQKEwlaSE9OR0xFTEUxFjAUBgNVBAsTDVpIT05HTEVMRS5DT00xJDAiBgkq
        hkiG9w0BCQEWFXN1cHBvcnRAemhvbmdsZWxlLmNvbTEWMBQGA1UEAxMNemhvbmds
        ZWxlLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKqf8l0ZwWA7
        qnv7kMLFgrMXxuFsCv4KkcD4Nrx2gWOfVYDYU/oVQWtz1nriAA1ldDTy7DJGD1Rw
        sMCEwPq4p0O7mZk2kBUbtb9tOp5E9nOoY9mCFhEpqptjH7TBmPzMckW9fzPefdBU
        SM9aGlALLwtoJkTTnngPmPtVUVmZ1qqo19zlRdAldbo2dY3ELpQxgBApG1orFO7Q
        gt03xNJOos1QkLv9nAMDxbWkObBkN3SKUAb8mNW3Qm9y411wgQeffnTnultsCI5j
        D4vdnjFmgOO66UPm8KrAYYwJYK/KhZxbzDqekJGQT6PlA/q5V4bwd3jLNSCMqaKl
        S1tfM8Lu8+sCAwEAAaOBpTCBojCBnwYDVR0RBIGXMIGUgg16aG9uZ2xlbGUuY29t
        ghNpcGFhcy56aG9uZ2xlbGUuY29tghttYXN0ZXIwLmlwYWFzLnpob25nbGVsZS5j
        b22CDyouemhvbmdsZWxlLmNvbYIVKi5pcGFhcy56aG9uZ2xlbGUuY29tgh0qLm1h
        c3RlcjAuaXBhYXMuemhvbmdsZWxlLmNvbYcE0jMau4cEfwAAATANBgkqhkiG9w0B
        AQUFAAOCAQEATMHQ6y+z3abki9qsNrLXcbvJZR3mg7TfIVwlgWEtP7nFxnjDkB3v
        7C6gRY2p3oMvZGhuwEsQX7DC1LJQnWRZVjnJwt4jIwch2XoGsTrXq40kDRg+wHXd
        kx+iE1U113CW1X4Rdyoc841ZKZthbzDNQQUdY19znN0jN+OxAaHUUc8hjgAasFAb
        0ZRs8kztQCz55M/QtQyYEc/iC8mkCBMW5aKPVODCqp6GklRX0UTwjSJarLlC/zMB
        x8nRQDAh5WAjIdzUrnKm97T1Pd1FPWer/dScY78qJMteBz97KwItWMTYjSmLiyag
        EswyntcjwpceMIdhLOQjWSZp6a9BGmGfZQ==
        -----END CERTIFICATE-----
      key: |
        -----BEGIN PRIVATE KEY-----
        MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCqn/JdGcFgO6p7
        +5DCxYKzF8bhbAr+CpHA+Da8doFjn1WA2FP6FUFrc9Z64gANZXQ08uwyRg9UcLDA
        hMD6uKdDu5mZNpAVG7W/bTqeRPZzqGPZghYRKaqbYx+0wZj8zHJFvX8z3n3QVEjP
        WhpQCy8LaCZE0554D5j7VVFZmdaqqNfc5UXQJXW6NnWNxC6UMYAQKRtaKxTu0ILd
        N8TSTqLNUJC7/ZwDA8W1pDmwZDd0ilAG/JjVt0JvcuNdcIEHn35057pbbAiOYw+L
        3Z4xZoDjuulD5vCqwGGMCWCvyoWcW8w6npCRkE+j5QP6uVeG8Hd4yzUgjKmipUtb
        XzPC7vPrAgMBAAECggEAdcd5LskTklE9it4JfFmIsgWstHi3UcuL90+fwRJwmIsp
        I4qw1UWM5haNLEALVzP8NnyljMKN3HT5nbtF1wxV8cxy568hYGDDYcONnijuksHf
        QwqoHurLKP4Qqd6ls4ORMhDv2Kcx4/f6Vp/U4AIIVHBtUj9d+XSS3pNzV015QE2y
        JvURLvm4CNiunj08xiP2KExoa9z/LTeqav6eb2353Gw/uqK5fBaLOGkMUbFnA8pH
        Saxr5nmf7N8JbEtYTm+TCL/TLKX8GhtakQxLoSFZAJ3ArYiDrg/3rFq4yohh2ftf
        vZAclI+6eHbiZ5Qj3D39Zac2VUCWVZi/PkhRb2CPoQKBgQDWykYFijdkMfObMfjQ
        sftE3YChsznI1umb49gHYkJpPKUfrWfOMXF9B/836YZ/Wq2qY/UL3McaMtzX0qp+
        UcI+zfPNI3K4U5uOVho3+waMxWQyi54isSgOGJObqAvevSUlKZd5MNliRkk6zIjP
        rjuCxI0D38HjRJK5gSJT7xv5GwKBgQDLXG3TdY4lQXn0wHdD20UbTC0er1C16wLm
        B/CKnYxRDAmNhvf5Bl+0GDRdHKN8WSpmIjgWwoxPeOMJmtn+g0ZjGlk8t4jPwDwU
        HG9j2aqQh2V4ZzWNUc0f2KYpxeXGXHzLoOvfG7KairgAZY7lFzK+E2GoCPlK9tf3
        vsuATWjtcQKBgEDqSzVba5hFnIl4FeoFEJrkkv7L6xfvFBWATAcXRFkH8iPbxbbE
        rLcMFq9wTazp2/jWUvYt2KLrYmF8EvkwfpN6rUd/gimBY08maLAolvcupTS9i6KS
        hjeUZ/AwXr4HzlUn99ax09FmyrURofuaffPssW3NT4z/aZTVGWnip0KnAoGAQGis
        7D2eYNRlIQzYeWh4cdXlsINMZ+HgUCURnYWazIyodefaoEfRhgPoidkpOpgvIpwR
        8bt6ny0lk4Q1KTRA1eChhOaIcWxsWt5KtXBaYl5P2BuwTWssMbr3neFtDi964y+7
        pTVrkyD+eDmyUYLQcn1G/+aftouKCZCneaKK6jECgYAuONkMqFKluG4a6nh+HRD/
        dQc5pf2QzTlhSJ9+dcnMu5qghlrVvK1aVuENbOTUzk2A6UIqJ4kGVaixln+Tatte
        PlRfR2XkMZlkg3k/8g/iI8Bz8bzOFD/RwZn6eaMaDgCAVXcxMsxKPcZLYMobJ7rL
        emSOjx+MYAM+sKB2j9vq2w==
        -----END PRIVATE KEY-----
      insecureEdgeTerminationPolicy: Redirect
#Jboss的mysql数据库部署配置
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "${MYSQL_SERVICE}-${APPNAME}"
    namespace: "${NAMESPACE}"
    creationTimestamp: null
    labels:
      app: "${APPNAME}"
      deploymentconfig: "${MYSQL_SERVICE}-${APPNAME}"
      group: "${NAMESPACE}"
      template: "${TEMPLATE}"
    annotations:
      description: The DeploymentConfig for Jboss MySQL
  spec:
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: "${TIME_OUT}"
      resources: {}
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - "${MYSQL_SERVICE}"
          from:
            kind: ImageStreamTag
            namespace: "${IMAGE_NAMESPACE}"
            name: mysql-57-centos7:5.8
          lastTriggeredImage: ''
    replicas: 1
    test: false
    selector:
      app: "${APPNAME}"
      deploymentconfig: "${MYSQL_SERVICE}-${APPNAME}"
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: "${APPNAME}"
          deploymentconfig: "${MYSQL_SERVICE}-${APPNAME}"
      spec:
        volumes:
          - name: "${MYSQL_SERVICE}-data"
            persistentVolumeClaim:
              claimName: "${MYSQL_SERVICE}-${APPNAME}-data"
        containers:
          - name: "${MYSQL_SERVICE}"
            image: ' '
            ports:
              - containerPort: 3306
                protocol: TCP
            env:
              - name: MYSQL_USER
                value: "${JBOSS_MYSQL_USER}"
              - name: MYSQL_PASSWORD
                value: "${JBOSS_MYSQL_PASSWORD}"
              - name: MYSQL_ROOT_PASSWORD
                value: "${JBOSS_MYSQL_ROOT_PASSWORD}"
              - name: MYSQL_DATABASE
                value: "${JBOSS_MYSQL_DATABASE}"
              - name: TZ
                value: "${SERVER_TIMEZONE}"
            resources:
              limits:
                cpu: '1'
                memory: 1Gi
            volumeMounts:
              - name: "${MYSQL_SERVICE}-data"
                mountPath: /var/lib/mysql/data
            livenessProbe:
              tcpSocket:
                port: 3306
              initialDelaySeconds: 30
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            readinessProbe:
              exec:
                command:
                  - /bin/sh
                  - '-i'
                  - '-c'
                  - >-
                    MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER
                    -D $MYSQL_DATABASE -e 'SELECT 1'
              initialDelaySeconds: 5
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            terminationMessagePath: "${LOG_MESSAGE}"
            imagePullPolicy: Always
            securityContext:
              capabilities: {}
              privileged: true
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        serviceAccountName: "${DEFAULT_NAME}"
        serviceAccount: "${DEFAULT_NAME}"
        securityContext: {}
  status: {}
#Jboss的部署配置
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "${APPNAME}"
    namespace: "${NAMESPACE}"
    creationTimestamp: null
    labels:
      app: "${APPNAME}"
  spec:
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: "${TIME_OUT}"
      resources: {}
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - "${APPNAME}"
          from:
            kind: ImageStreamTag
            namespace: "${NAMESPACE}"
            name: "${APPNAME}:latest"
          lastTriggeredImage: ''
    replicas: 1
    test: false
    selector:
      app: "${APPNAME}"
      deploymentconfig: "${APPNAME}"
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: "${APPNAME}"
          deploymentconfig: "${APPNAME}"
      spec:
        containers:
          - name: "${APPNAME}"
            image: ' '
            ports:
              - containerPort: 8080
                protocol: TCP
              - containerPort: 8443
                protocol: TCP
              - containerPort: 8778
                protocol: TCP
            env:
              - name: MYSQL_USER
                value: "${JBOSS_MYSQL_USER}"
              - name: MYSQL_PASSWORD
                value: "${JBOSS_MYSQL_PASSWORD}"
              - name: MYSQL_DATABASE
                value: "${JBOSS_MYSQL_DATABASE}"
              - name: TZ
                value: "${SERVER_TIMEZONE}"
            resources: {}
            livenessProbe:
              httpGet:
                path: /
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 15
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            readinessProbe:
              httpGet:
                path: /
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 15
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            terminationMessagePath: "${LOG_MESSAGE}"
            imagePullPolicy: Always
            securityContext:
              capabilities: {}
              privileged: true
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        serviceAccountName: "${DEFAULT_NAME}"
        serviceAccount: "${DEFAULT_NAME}"
        securityContext: {}
  status: {}
#Jboss的mysql数据库服务
- apiVersion: v1
  kind: Service
  metadata:
    name: "${NAMESPACE}-${MYSQL_SERVICE}-${APPNAME}"
    namespace: "${NAMESPACE}"
    creationTimestamp: null
    labels:
      app: "${APPNAME}"
      group: "${NAMESPACE}"
      template: "${TEMPLATE}"
    annotations:
      description: the Service for Jboss MySQL
  spec:
    ports:
      - name: "${MYSQL_SERVICE}-tcp"
        protocol: TCP
        port: 3306
        targetPort: 3306
    selector:
      app: "${APPNAME}"
      deploymentconfig: "${MYSQL_SERVICE}-${APPNAME}"
    clusterIP: 172.30.101.13
    type: ClusterIP
    sessionAffinity: None
#Jboss的服务
- apiVersion: v1
  kind: Service
  metadata:
    name: "${NAMESPACE}-${APPNAME}"
    namespace: "${NAMESPACE}"
    creationTimestamp: null
    labels:
      app: "${APPNAME}"
      group: "${NAMESPACE}"
      template: "${TEMPLATE}"
    annotations:
      description: the Service for Jboss
      service.alpha.openshift.io/dependencies: '[{"name": "${NAMESPACE}-${MYSQL_SERVICE}-${APPNAME}", "namespace": "", "kind": "Service"}]'
      service.openshift.io/infrastructure: 'true'
  spec:
    ports:
      - name: "${APPNAME}-tcp"
        protocol: TCP
        port: 8080
        targetPort: 8080
    selector:
      app: "${APPNAME}"
      deploymentconfig: "${APPNAME}"
    clusterIP: 172.30.101.12
    type: ClusterIP
    sessionAffinity: None
