#部署zk-finance2的List
apiVersion: v1
kind: List
items:
#zk-finance2数据库存储
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    creationTimestamp: null
    labels:
      group: dev
      project: dev
      provider: "zk-finance2-mysql"
    name: "dev-zk-finance2-mysql-pv"
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: "zk-finance2-mysql-data"
      namespace: dev
    hostPath:
      path: "/mnt/data/dev-storage/zk-finance2-mysql/"
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      group: dev
      project: dev
      provider: "zk-finance2-mysql"
    name: "zk-finance2-mysql-data"
    namespace: dev
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: "dev-zk-finance2-mysql-pv"
