#部署nginx模板
kind: Template
apiVersion: v1
metadata:
  name: nginx-persistent
  creationTimestamp: null
  annotations:
    openshift.io/display-name: Nginx App (Persistent)
    description: |-
      All resource for nginx, with persistent storage.
    iconClass: icon-jenkins
    tags: nginx
labels:
  template: dev-nginx-persistent-template
  group: dev
message: Simple deploy Nginx App
#参数
parameters:
#当前项目名称
- name: NAMESPACE
  displayName: Current Project Namespace
  description: Name of the current project namespace.
  value: dev
#当前模板名称
- name: TEMPLATE
  displayName: Current Template Name
  description: Name of the current template name.
  value: dev-nginx-persistent-template
#默认服务账户名称
- name: DEFAULT_NAME
  displayName: Default ServiceAccount Name
  description: Name of the default serviceaccount.
  value: default
#Nginx容器名称
- name: NGINX_SERVICE
  displayName: Nginx Service Name
  description: The name of the OpenShift Service exposed for the Nginx container.
  value: nginx
#日志信息存放路径
- name: LOG_MESSAGE
  displayName: Termination Message Path
  description: Maximum amount of memory the container can use.
  value: /dev/termination-log
#部署超时
- name: TIME_OUT
  displayName: timeout seconds
  description: Deployment params timeout seconds
  value: '600'
#镜像所在项目名称
- name: IMAGE_NAMESPACE
  displayName: The ImageStream Namespace
  description: The OpenShift Namespace where the ImageStream resides.
  value: openshift
#CST时区
- name: SERVER_TIMEZONE
  displayName: CST Timezone
  description: China Standard Time for POD
  value: Asia/Shanghai
objects:
#创建角色绑定
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    labels:
      group: "${NAMESPACE}"
      template: "${TEMPLATE}"
    name: "${DEFAULT_NAME}_edit"
    namespace: "${NAMESPACE}"
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: "${DEFAULT_NAME}"
    namespace: "${NAMESPACE}"
#Nginx的路由
- apiVersion: v1
  kind: Route
  metadata:
    name: "${NGINX_SERVICE}"
    namespace: "${NAMESPACE}"
    creationTimestamp: null
    labels:
      app: "${NGINX_SERVICE}"
    annotations:
      description: Route for Nginx http service.
      openshift.io/host.generated: 'true'
  spec:
    to:
      kind: Service
      name: "${NGINX_SERVICE}"
      weigth: 100
    port:
      targetPort: "${NGINX_SERVICE}-tcp"
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
#Nginx存储
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    creationTimestamp: null
    labels:
      group: "${NAMESPACE}"
      project: "${NAMESPACE}"
      provider: "${NGINX_SERVICE}"
      template: "${TEMPLATE}"
    name: "${NAMESPACE}-${NGINX_SERVICE}-pv"
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 20Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: "${NGINX_SERVICE}-conf"
      namespace: "${NAMESPACE}"
    hostPath:
      path: "/var/lib/docker/data/${NGINX_SERVICE}-storage/${NAMESPACE}/"
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      group: "${NAMESPACE}"
      project: "${NAMESPACE}"
      provider: "${NGINX_SERVICE}"
      template: "${TEMPLATE}"
    name: "${NGINX_SERVICE}-conf"
    namespace: "${NAMESPACE}"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
    volumeName: "${NAMESPACE}-${NGINX_SERVICE}-pv"
#Nginx的部署配置
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "${NGINX_SERVICE}"
    namespace: "${NAMESPACE}"
    creationTimestamp: null
    labels:
      app: "${NGINX_SERVICE}"
      group: "${NAMESPACE}"
      template: "${TEMPLATE}"
    annotations:
      description: The DeploymentConfig for Nginx
  spec:
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: "${TIME_OUT}"
      resources: {}
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - "${NGINX_SERVICE}"
          from:
            kind: ImageStreamTag
            namespace: "${IMAGE_NAMESPACE}"
            name: nginx:1.13
          lastTriggeredImage: ''
    replicas: 1
    test: false
    selector:
      app: "${NGINX_SERVICE}"
      deploymentconfig: "${NGINX_SERVICE}"
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: "${NGINX_SERVICE}"
          deploymentconfig: "${NGINX_SERVICE}"
      spec:
        volumes:
          - name: "${NGINX_SERVICE}-conf"
            persistentVolumeClaim:
              claimName: "${NGINX_SERVICE}-conf"
          - name: "${NGINX_SERVICE}-html"
            persistentVolumeClaim:
              claimName: "${NGINX_SERVICE}-html"
        containers:
          - name: "${NGINX_SERVICE}"
            image: ' '
            ports:
              - containerPort: 80
                protocol: TCP
            env:
              - name: TZ
                value: "${SERVER_TIMEZONE}"
            resources: {}
            volumeMounts:
              - name: "${NGINX_SERVICE}-data"
                mountPath: /etc/nginx
              - name: "${NGINX_SERVICE}-html"
                mountPath: /usr/share/nginx/html
            livenessProbe:
              httpGet:
                path: /
                port: 80
                scheme: HTTP
              initialDelaySeconds: 30
              timeoutSeconds: 5
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 5
            readinessProbe:
              httpGet:
                path: /
                port: 80
                scheme: HTTP
              initialDelaySeconds: 30
              timeoutSeconds: 5
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 5
            terminationMessagePath: "${LOG_MESSAGE}"
            imagePullPolicy: Always
            securityContext:
              capabilities: {}
              privileged: true
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        serviceAccountName: "${DEFAULT_NAME}"
        serviceAccount: "${DEFAULT_NAME}"
        securityContext: {}
  status: {}
#Nginx的服务
- apiVersion: v1
  kind: Service
  metadata:
    name: "${NGINX_SERVICE}"
    namespace: "${NAMESPACE}"
    creationTimestamp: null
    labels:
      app: "${NGINX_SERVICE}"
      group: "${NAMESPACE}"
      template: "${TEMPLATE}"
    annotations:
      description: the Service for Nginx
  spec:
    ports:
      - name: "${NGINX_SERVICE}-tcp"
        protocol: TCP
        port: 8081
        targetPort: 8081
    selector:
      app: "${NGINX_SERVICE}"
      deploymentconfig: "${NGINX_SERVICE}"
    clusterIP: 172.30.100.13
    type: ClusterIP
    sessionAffinity: None
