#部署subversion模板
kind: Template
apiVersion: v1
metadata:
  name: subversion-persistent
  creationTimestamp: null
  annotations:
    openshift.io/display-name: Subversion App (Persistent)
    description: |-
      All resource for subversion, with persistent storage.
    iconClass: icon-jenkins
    tags: subversion
labels:
  template: cicd-subversion-persistent-template
  group: cicd
message: Simple deploy Subversion App
#参数
parameters:
#当前项目名称
- name: NAMESPACE
  displayName: Current Project Namespace
  description: Name of the current project namespace.
  value: cicd
#当前模板名称
- name: TEMPLATE
  displayName: Current Template Name
  description: Name of the current template name.
  value: cicd-subversion-persistent-template
#默认服务账户名称
- name: DEFAULT_NAME
  displayName: Default ServiceAccount Name
  description: Name of the default serviceaccount.
  value: default
#Subversion容器名称
- name: SUBVERSION_SERVICE
  displayName: Subversion Service Name
  description: The name of the OpenShift Service exposed for the Subversion container.
  value: subversion
#日志信息存放路径
- name: LOG_MESSAGE
  displayName: Termination Message Path
  description: Maximum amount of memory the container can use.
  value: /dev/termination-log
#部署超时
- name: TIME_OUT
  displayName: timeout seconds
  description: Deployment params timeout seconds
  value: '600'
#镜像所在项目名称
- name: IMAGE_NAMESPACE
  displayName: Cicd ImageStream Namespace
  description: The OpenShift Namespace where the Cicd ImageStream resides.
  value: openshift
#CST时区
- name: SERVER_TIMEZONE
  displayName: CST Timezone
  description: China Standard Time for POD
  value: Asia/Shanghai
objects:
#创建角色绑定
- apiVersion: v1
  groupNames: null
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    labels:
      group: "${NAMESPACE}"
      template: "${TEMPLATE}"
    name: "${DEFAULT_NAME}_edit"
    namespace: "${NAMESPACE}"
  roleRef:
    name: edit
  subjects:
  - kind: ServiceAccount
    name: "${DEFAULT_NAME}"
    namespace: "${NAMESPACE}"
#Subversion的路由
- apiVersion: v1
  kind: Route
  metadata:
    name: "${SUBVERSION_SERVICE}-http"
    namespace: "${NAMESPACE}"
    creationTimestamp: null
    labels:
      app: "${SUBVERSION_SERVICE}"
    annotations:
      description: Route for Subversion http service.
      openshift.io/host.generated: 'true'
  spec:
    host: svn.ipaas.zhonglele.com
    to:
      kind: Service
      name: "${SUBVERSION_SERVICE}"
      weigth: 100
    port:
      targetPort: "${SUBVERSION_SERVICE}-80-tcp"
    wildcardPolicy: None
#Subversion存储
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    creationTimestamp: null
    labels:
      group: "${NAMESPACE}"
      project: "${NAMESPACE}"
      provider: "${SUBVERSION_SERVICE}"
      template: "${TEMPLATE}"
    name: "${NAMESPACE}-${SUBVERSION_SERVICE}-1-pv"
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: "${SUBVERSION_SERVICE}-1"
      namespace: "${NAMESPACE}"
    hostPath:
      path: "/mnt/data/cicd-storage/subversion/subversion-1/"
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      group: "${NAMESPACE}"
      project: "${NAMESPACE}"
      provider: "${SUBVERSION_SERVICE}"
      template: "${TEMPLATE}"
    name: "${SUBVERSION_SERVICE}-1"
    namespace: "${NAMESPACE}"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    volumeName: "${NAMESPACE}-${SUBVERSION_SERVICE}-1-pv"
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    creationTimestamp: null
    labels:
      group: "${NAMESPACE}"
      project: "${NAMESPACE}"
      provider: "${SUBVERSION_SERVICE}"
      template: "${TEMPLATE}"
    name: "${NAMESPACE}-${SUBVERSION_SERVICE}-2-pv"
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 15Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: "${SUBVERSION_SERVICE}-2"
      namespace: "${NAMESPACE}"
    hostPath:
      path: "/mnt/data/cicd-storage/subversion/subversion-2/"
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      group: "${NAMESPACE}"
      project: "${NAMESPACE}"
      provider: "${SUBVERSION_SERVICE}"
      template: "${TEMPLATE}"
    name: "${SUBVERSION_SERVICE}-2"
    namespace: "${NAMESPACE}"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 15Gi
    volumeName: "${NAMESPACE}-${SUBVERSION_SERVICE}-2-pv"
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    creationTimestamp: null
    labels:
      group: "${NAMESPACE}"
      project: "${NAMESPACE}"
      provider: "${SUBVERSION_SERVICE}"
      template: "${TEMPLATE}"
    name: "${NAMESPACE}-${SUBVERSION_SERVICE}-3-pv"
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 1Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: "${SUBVERSION_SERVICE}-3"
      namespace: "${NAMESPACE}"
    hostPath:
      path: "/mnt/data/cicd-storage/subversion/subversion-3/"
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      group: "${NAMESPACE}"
      project: "${NAMESPACE}"
      provider: "${SUBVERSION_SERVICE}"
      template: "${TEMPLATE}"
    name: "${SUBVERSION_SERVICE}-3"
    namespace: "${NAMESPACE}"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    volumeName: "${NAMESPACE}-${SUBVERSION_SERVICE}-3-pv"
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    creationTimestamp: null
    labels:
      group: "${NAMESPACE}"
      project: "${NAMESPACE}"
      provider: "${SUBVERSION_SERVICE}"
      template: "${TEMPLATE}"
    name: "${NAMESPACE}-${SUBVERSION_SERVICE}-4-pv"
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 5Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: "${SUBVERSION_SERVICE}-4"
      namespace: "${NAMESPACE}"
    hostPath:
      path: "/mnt/data/cicd-storage/subversion/subversion-4/"
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      group: "${NAMESPACE}"
      project: "${NAMESPACE}"
      provider: "${SUBVERSION_SERVICE}"
      template: "${TEMPLATE}"
    name: "${SUBVERSION_SERVICE}-4"
    namespace: "${NAMESPACE}"
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    volumeName: "${NAMESPACE}-${SUBVERSION_SERVICE}-4-pv"
#Subversion的部署配置
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: "${SUBVERSION_SERVICE}"
    namespace: "${NAMESPACE}"
    creationTimestamp: null
    labels:
      app: "${SUBVERSION_SERVICE}"
      group: "${NAMESPACE}"
      template: "${TEMPLATE}"
    annotations:
      description: The DeploymentConfig for Subversion
  spec:
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: "${TIME_OUT}"
      resources: {}
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - "${SUBVERSION_SERVICE}"
        from:
          kind: ImageStreamTag
          namespace: "${IMAGE_NAMESPACE}"
          name: subversion:latest
        lastTriggeredImage: ''
    replicas: 1
    test: false
    selector:
      app: "${SUBVERSION_SERVICE}"
      deploymentconfig: "${SUBVERSION_SERVICE}"
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: "${SUBVERSION_SERVICE}"
          deploymentconfig: "${SUBVERSION_SERVICE}"
      spec:
        volumes:
          - name: "${SUBVERSION_SERVICE}-1"
            persistentVolumeClaim:
              claimName: "${SUBVERSION_SERVICE}-1"
          - name: "${SUBVERSION_SERVICE}-2"
            persistentVolumeClaim:
              claimName: "${SUBVERSION_SERVICE}-2"
          - name: "${SUBVERSION_SERVICE}-3"
            persistentVolumeClaim:
              claimName: "${SUBVERSION_SERVICE}-3"
          - name: "${SUBVERSION_SERVICE}-4"
            persistentVolumeClaim:
              claimName: "${SUBVERSION_SERVICE}-4"
        containers:
          - name: "${SUBVERSION_SERVICE}"
            image: ' '
            ports:
              - containerPort: 80
                protocol: TCP
              - containerPort: 443
                protocol: TCP
            env:
              - name: CONTEXT_PATH
                value: /
              - name: TZ
                value: "${SERVER_TIMEZONE}"
            resources: {}
            volumeMounts:
              - name: "${SUBVERSION_SERVICE}-1"
                mountPath: /etc/apache/dav_svn
              - name: "${SUBVERSION_SERVICE}-2"
                mountPath: /var/local/svn
              - name: "${SUBVERSION_SERVICE}-3"
                mountPath: /var/svn-backup
              - name: "${SUBVERSION_SERVICE}-4"
                mountPath: /etc/apache2
            livenessProbe:
              httpGet:
                path: /
                port: 80
                scheme: HTTP
              initialDelaySeconds: 60
              timeoutSeconds: 5
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 5
            readinessProbe:
              httpGet:
                path: /
                port: 80
                scheme: HTTP
              initialDelaySeconds: 60
              timeoutSeconds: 5
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 5
            terminationMessagePath: "${LOG_MESSAGE}"
            imagePullPolicy: IfNotPresent
            securityContext:
              capabilities: {}
              privileged: true
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        serviceAccountName: "${DEFAULT_NAME}"
        serviceAccount: "${DEFAULT_NAME}"
        securityContext: {}
  status: {}
#Subversion的服务
- apiVersion: v1
  kind: Service
  metadata:
    name: "${SUBVERSION_SERVICE}"
    namespace: "${NAMESPACE}"
    creationTimestamp: null
    labels:
      app: "${SUBVERSION_SERVICE}"
      group: "${NAMESPACE}"
      template: "${TEMPLATE}"
    annotations:
      description: the Service for Subversion
  spec:
    ports:
      - name: "${SUBVERSION_SERVICE}-80-tcp"
        protocol: TCP
        port: 80
        targetPort: 80
      - name: "${SUBVERSION_SERVICE}-443-tcp"
        protocol: TCP
        port: 443
        targetPort: 443
    selector:
      app: "${SUBVERSION_SERVICE}"
      deploymentconfig: "${SUBVERSION_SERVICE}"
    clusterIP: 172.30.100.17
    type: ClusterIP
    sessionAffinity: None
